name: parakeet-genai-stack

# Embeddings generation then start the application:
# docker compose -f compose.dev.yml --profile generation --profile application up --build 

# Start the application only:
# docker compose -f compose.dev.yml --profile application up --build 

services:

  gitingest:
    profiles: [generation]
    build:
      context: ./gitingest
      dockerfile: Dockerfile
    environment:
      - GITHUB_REPOSITORY=https://github.com/parakeet-nest/parakeet
      - INCLUDE_PATTERNS=*.go
      #- INCLUDE_PATTERNS=*.go,*.md
    volumes:
      - ./data:/app/data

  elasticsearch:
    profiles: [generation, application]
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - ES_JAVA_OPTS=-Xmx8g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=500ms"]
      retries: 300
      interval: 1s

  elasticsearch_settings:
    profiles: [generation, application]
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch_settings
    restart: 'no'
    command: >
      bash -c '        
        echo "Setup the kibana_system password";
        until curl -s -u "elastic:${ELASTIC_PASSWORD}" -X POST http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"${ELASTIC_PASSWORD}\"}" -H "Content-Type: application/json" | grep -q "^{}"; do sleep 5; done;
      '

  kibana:
    profiles: [generation, application]
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    depends_on:
      elasticsearch_settings:
        condition: service_completed_successfully
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOSTS}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/api/status | grep -q 'All services are available'"]
      retries: 300
      interval: 1s

  download-local-llm-embeddings:
    profiles: [generation, application]
    image: curlimages/curl:8.6.0
    #entrypoint: ["curl", "http://host.docker.internal:11434/api/pull", "-d", '{"name": "nomic-embed-text:latest"}']
    entrypoint:
      - "sh"
      - "-c"
      - 'curl "${OLLAMA_BASE_URL}/api/pull" -d "{\"name\": \"${LLM_EMBEDDINGS}\"}"'

  create-embeddings:
    profiles: [generation]
    build:
      context: ../..  # Points to parakeet root directory
      dockerfile: examples/72-gitingest-es/create-embeddings/Dockerfile.dev
    environment:
      - CONTENT_PATH=/app/data/content.txt
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM_EMBEDDINGS=${LLM_EMBEDDINGS}
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_INDEX=${ELASTIC_INDEX}
    volumes:
      - ./data:/app/data
    depends_on:
      download-local-llm-embeddings:
        condition: service_completed_successfully
      gitingest:
        condition: service_completed_successfully
      kibana:
        condition: service_started
      elasticsearch:
        condition: service_started


  download-local-llm:
    profiles: [application]
    image: curlimages/curl:8.6.0
    #entrypoint: ["curl", "http://host.docker.internal:11434/api/pull", "-d", '{"name": "qwen2.5:7b"}']
    entrypoint:
      - "sh"
      - "-c"
      - 'curl "${OLLAMA_BASE_URL}/api/pull" -d "{\"name\": \"${LLM_CHAT}\"}"'

  backend:
    profiles: [application]
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - CONTENT_PATH=/app/data/tree.txt
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM_CHAT=${LLM_CHAT}
      - LLM_EMBEDDINGS=${LLM_EMBEDDINGS}
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_INDEX=${ELASTIC_INDEX}
      - MAX_SIMILARITIES=20
      - SYSTEM_INSTRUCTIONS= |-
          You are an expert in the codebase of the Parakeet project. 
          Parakeeet is a Golang library to develop GenAI application with Ollama.
          You are asked to provide a brief explanation of the codebase and answer questions about the codebase.
          Use only the codebase and the documentation to answer the questions.
          The system will provide you with the most relevant code snippets to help you answer the questions.
    volumes:
      - ./data:/app/data
    depends_on:
      download-local-llm-embeddings:
        condition: service_completed_successfully
      download-local-llm:
        condition: service_completed_successfully
      kibana:
        condition: service_started
      elasticsearch:
        condition: service_started
    develop:
      watch:
        - action: rebuild
          path: ./backend/main.go

  frontend:
    profiles: [application]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 9090:8501
    environment:
      - BACKEND_SERVICE_URL=http://backend:5050
      - PAGE_TITLE=ðŸ¤“ AMA about your source code!
      - PAGE_HEADER=Made with ðŸ’– and probably too much caffeine
      - PAGE_ICON=ðŸ¤–
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./frontend/app.py

